export const LIST_SUCCESS = "LIST_SUCCESS";
export const LIST_BEGIN = "LIST_BEGIN";
export const LIST_FAILURE = "LIST_FAILURE";

export const POPULAR_LIST_SUCCESS = "POPULAR_LIST_SUCCESS";
export const POPULAR_LIST_BEGIN = "POPULAR_LIST_BEGIN";
export const POPULAR_LIST_FAILURE = "POPULAR_LIST_FAILURE";

export const DISCOVERTVSHOW_LIST_SUCCESS = "DISCOVERTVSHOW_LIST_SUCCESS";
export const DISCOVERTVSHOW_LIST_BEGIN = "DISCOVERTVSHOW_LIST_BEGIN";
export const DISCOVERTVSHOW_LIST_FAILURE = "DISCOVERTVSHOW_LIST_FAILURE";

export const DISCOVERMOVIE_LIST_BEGIN = "DISCOVERMOVIE_LIST_BEGIN";
export const DISCOVERMOVIE_LIST_FAILURE = "DISCOVERMOVIE_LIST_FAILURE";
export const DISCOVERMOVIE_LIST_SUCCESS = "DISCOVERMOVIE_LIST_SUCCESS";

export const TOPRATED_LIST_SUCCESS = "TOPRATED_LIST_SUCCESS";
export const TOPRATED_LIST_BEGIN = "TOPRATED_LIST_BEGIN";
export const TOPRATED_LIST_FAILURE = "TOPRATED_LIST_FAILURE";

export const UPCOMMING_LIST_BEGIN = "UPCOMMING_LIST_BEGIN";
export const UPCOMMING_LIST_SUCCESS = "UPCOMMING_LIST_SUCCESS";
export const UPCOMMING_LIST_FAILURE = "UPCOMMING_LIST_FAILURE";

export const FETCH_MOVIE_BEGIN = "FETCH_MOVIE_BEGIN";
export const FETCH_MOVIE_SUCCESS = "FETCH_MOVIE_SUCCESS";
export const FETCH_MOVIE_FAILURE = "FETCH_MOVIE_FAILURE";

export const FETCH_MOVIE_CAST_BEGIN = "FETCH_MOVIE_CAST_BEGIN";
export const FETCH_MOVIE_CAST_SUCCESS = "FETCH_MOVIE_CAST_SUCCESS";
export const FETCH_MOVIE_CAST_FAILURE = "FETCH_MOVIE_CAST_FAILURE";

export const FETCH_TVSHOW_BEGIN = "FETCH_TVSHOW_BEGIN";
export const FETCH_TVSHOW_SUCCESS = "FETCH_TVSHOW_SUCCESS";
export const FETCH_TVSHOW_FAILURE = "FETCH_TVSHOW_FAILURE";

export const FETCH_TVSHOW_CAST_BEGIN = "FETCH_TVSHOW_CAST_BEGIN";
export const FETCH_TVSHOW_CAST_SUCCESS = "FETCH_TVSHOW_CAST_SUCCESS";
export const FETCH_TVSHOW_CAST_FAILURE = "FETCH_TVSHOW_CAST_FAILURE";

export const FETCH_SEARCH_RESULT_BEGIN = "FETCH_SEARCH_RESULT_BEGIN";
export const FETCH_SEARCH_RESULT_SUCCESS = "FETCH_SEARCH_RESULT_SUCCESS";
export const FETCH_SEARCH_RESULT_FAILURE = "FETCH_SEARCH_RESULT_FAILURE";

export const FETCH_RECOMMENDATION_BEGIN = "FETCH_RECOMMENDATION_BEGIN";
export const FETCH_RECOMMENDATION_SUCCESS = "FETCH_RECOMMENDATION_SUCCESS";
export const FETCH_RECOMMENDATION_FAILURE = "FETCH_RECOMMENDATION_FAILURE";
